modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/dima-dencep/translationfallbacks/issues"
license = "OSL-3.0"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "translationfallbacks"
version = "${version}"
displayURL = "https://github.com/dima-dencep/translationfallbacks"
displayName = "Translation Fallbacks"
authors = "dima_dencep"
description = "Allows translations to have multiple fallbacks"

[[mixins]]
config = "translationfallbacks.mixins.json"
