unimined.minecraft {
    combineWith(project(":common").sourceSets.main)

    fabric {
        loader rootProject.fabric_version
        accessWidener project(":common").file("src/main/resources/translationfallbacks.classtweaker")
    }
}

unimined.minecraft(sourceSets.test) {
    combineWith(sourceSets.main)
}

dependencies {
    testImplementation "net.fabricmc:fabric-loader-junit:${rootProject.fabric_version}"
}

test {
    include '/tests/**'
    useJUnitPlatform()
}

testJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar {
    archiveClassifier.set null
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = "TranslationFallbacksFabric"
            from components.java
        }
    }
}
