plugins {
    id "xyz.wagyourtail.unimined" version "1.4.2+redlance.3" apply false
}

subprojects {
    apply plugin: "xyz.wagyourtail.unimined"

    unimined.minecraft(sourceSets.main, true) {
        version rootProject.minecraft_version
    }

    processResources {
        inputs.property "version", version

        filesMatching(["META-INF/neoforge.mods.toml", "fabric.mod.json"]) {
            expand "version": version
        }
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "java-library"
    apply plugin: "maven-publish"

    base.archivesName = rootProject.archives_base_name
    version = "${rootProject.mod_version}+mc.${rootProject.minecraft_version}"
    group = rootProject.maven_group

    repositories {
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
            content {
                excludeGroupByRegex "org.parchmentmc"
            }
        }
        maven {
            name = "Maven for PR #2975" // https://github.com/neoforged/NeoForge/pull/2975
            url = uri("https://prmaven.neoforged.net/NeoForge/pr2975")
            content {
                includeModule("net.neoforged", "neoforge")
                includeModule("net.neoforged", "testframework")
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release.set 25
    }

    java {
        withSourcesJar()
    }

    publishing {
        repositories {
            maven {
                name = "RedlanceMinecraft"
                url = "https://repo.redlance.org/public"
                credentials {
                    username = "dima_dencep"
                    password = System.getenv("MAVEN_PASSWORD")
                }
            }
        }
    }
}