# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Properties
    minecraft_version = 26.1-snapshot-10
    fabric_version = 0.18.4
    neoforge_version = 26.2.0.76

# Mod Properties
    mod_version = 1.2.0
    maven_group = org.redlance.dima_dencep.mods
    archives_base_name = TranslationFallbacks

# Dependencies
