name: "publish"
on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew test publish
        env:
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
